### PR TITLE
ENG-206 Implement Block Reversion 

### PR DESCRIPTION
**Pull request by 0xmovses**
### Description
Ticket https://movement.atlassian.net/browse/ENG-206

Specifically, from [RFC-2](https://github.com/movementlabsxyz/org/blob/main/rfc/rfc-m2-block-reversion/rfc-m2-aptos-block-reversion.md) :

> Importantly, standard persistence is implement over RocksDB and does not provide immediate reversion controls. Thus, the reversion controls would need to be implemented in a separate DbWriter trait object that can then be added to [DbReaderWriter](https://github.com/aptos-labs/aptos-core/blob/3d4e63c51d50b6dd3d421663089153df5083747a/storage/storage-interface/src/lib.rs#L578). The [AptosDB](https://github.com/aptos-labs/aptos-core/blob/3d4e63c51d50b6dd3d421663089153df5083747a/storage/aptosdb/src/db/include/aptosdb_internal.rs#L4) [DbWriter implementation](https://github.com/aptos-labs/aptos-core/blob/3d4e63c51d50b6dd3d421663089153df5083747a/storage/aptosdb/src/db/include/aptosdb_writer.rs#L4) does not directly wrap methods that would enable reversion. These would need to be implemented.

### Testing
Three new unit tests have been added:
- `test_revert_last_commit`
- `test_revert_nth_commit`
- `test_revert_last_commit_should_fail_with_wrong_hash`

Run all the aptosdb tests:
`cargo test --package aptos-db --lib -- db::aptosdb_test --nocapture`

### CODE REVIEW

**Comment by l-monninger** [comment]
How would I use `revert_last_commit` to revert to an arbitrary commit?

**Comment by 0xmovses** [comment]
I think it should work for an arbitrary commit as opposed to just the last, but I'll probably write a test for that case and update the name of the method to improve the semantics there.

**Comment by 0xmovses** [comment]
@l-monninger I added a new test  `cargo test --package aptos-db --lib -- db::aptosdb_test::test_nth_last_commit --exact --nocapture `

**Comment by 0xmovses** [comment]
Fixed the bug with state pruning when reverting nth commit. 

However, sometimes (for me something like 1 / 10)  I see this error:
````
`called `Result::unwrap()` on an `Err` value: Other("Gap in epoch history. Trying to put in LedgerInfo in epoch: 2, current epoch: 3")`
```

I'm not sure if this is blocking or not for this to get merged. Can create a separate ticket to track this new bug.

**Comment by l-monninger** [comment]
@0xmovses Generally, I think we want to do as much early loading testing as possible here (even in integration tests). The issues that we had with the M1 implementation showed up under load.

**Comment by l-monninger** [comment]
This is looking pretty good and working for me. I want to spend some more time validating the tests. But, we should probably progress to checking this e2e in movementlabsxyz/movement. We can close this once we're satisfied with integration there.

**Comment by 0xmovses** [comment]
@l-monninger ready for re-review. Once this goes in I'll update the companion PR https://github.com/movementlabsxyz/movement/pull/46 to use `branch = "monza"` instead of `rev = "foo"`

**Comment by 0xmovses** [comment]
This was also fixed: 

> ... occasionally (for me something like 1 / 10) I see this error:
> 
> ```
> `called `Result::unwrap()` on an `Err` value: Other("Gap in epoch history. Trying to put in LedgerInfo in epoch: 2, current epoch: 3")`
> ```

**Pull request merged**
